---

- name: "nom playbook"
  hosts: all
  become: yes
  tasks:
  - name: "creation de cisco"
    user:
      name: "cisco"
      state: present
      group: sudo
      password: "{{ 'password'| password_hash('sha512') }}" 

